# Generated by Django 2.2.6 on 2020-01-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200116_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='null', max_length=50, primary_key=True, serialize=False),
        ),
    ]
